### PR TITLE
new expand widget, new widget placement options, and css restructuring

### PR DESCRIPTION
**Pull request by tmcgee**
Sorry for the big PR. These were all related and I was on a roll...

Details in commits. Highlights for release notes here: 

* New - `ExpandPane` widget - container widget like `titlePane` and `floating`. new widget type is `expandPane`. Widget collapses down to an icon when title pane is closed. It behaves similar to expand widget in 4.x API. `expand` will be supported in 4.x as a separate widget type. 

**Example:**
image
image

* New - Layout for map ui widgets. can place widgets in 4 corners of map as well as inset at 4 corners.  this includes a new `ui` wisget type. shortcuts like `top-left` and `bottom-right` sames as the 4.x API. examples provided in viewer.js

* New - widgets can be placed into other other widgets (referenced and by ID), DOMNodes (referenced and by ID) or by css selector like `.cmv-inset .cmv-top-right'.  Older approach of replacing DOMNodes is still supported. divs in `mapTemplate.html` have been updated.

* New - document body uses Flex Box so only the appHeader height needs to be adjusted. BorderPane will automatically use the rest of the page.

* New - Brand icon will resize automatically if header height is changed.

* Fix - creation of `layout` widgets was lost in a previous restructuring of Mixins. layout widgets can be loaded before the map and can be used as containers for other widgets. ExpandPane is one example of this. Growler widget is a layout widget in viewer.js

* Restructured much of _WidgetMixin for ease of maintenance.

* Renamed main.css to app.css for consistentcy

* Renamed cmv-theme-overrides.css to cmv.css

* Restructured css files. Only appHeader and pane sizing is in app.css file. All other css is part of cmv "theme"

### CODE REVIEW

**Comment by tmcgee** [comment]
I have tested the changes included in this PR with:

* [my cmv-widgets](https://github.com/tmcgee/cmv-widgets/)
* [cmv-calcite-maps](https://github.com/cmv/cmv-calcite-maps/)
* [cmv-wab-widgets](https://github.com/cmv/cmv-wab-widgets/)

I corrected one issue that affected cmv-calcite-maps. No other apparent issues.

**Comment by green3g** [comment]
Should we set a max width on the widgets?

image

**Comment by tmcgee** [comment]
I've considered that. The divs containing the ui widgets have no width so we can't use a percentage value. I was trying to avoid a hard-coded max-width in pixels used for all widgets within the ui divs. I suppose it can be done with a series of width breakpoints similar to what I did for the mobile sidebar. Not sure I like those either but it was a start.

In the configuration, you can set a max-width for any widget - that includes the `expandPane` parent (or `titlePane` or `contentPane`) or set it for the widget(s) contained within the pane.

**Comment by tmcgee** [comment]
As discussed in PM with @roemhildtg , I changed to use a percentage of the viewport width (i.e. 30vw) for the max-width of map ui widgets. Good addition. That will work for the vast majority of use cases when the map is the full width of the screen. If a developer places the map within a div resulting in a smaller map width, they can customize the css to suit their needs.

image

**Comment by green3g** [comment]
This is awesome.

**Pull request merged**
