### PR TITLE
Remove legacy viewer folder from build

### PR DESCRIPTION
**Pull request by tmcgee**
Also minor updates to the package.json file.

### CODE REVIEW

**Comment by tmcgee** [comment]
The `Details` [link](https://deploy-preview-858--cmv-app.netlify.com/) for the `deploy/netlify` check is proof this works. :smile:

**Review by green3g — APPROVED** [review]

**Comment by tmcgee** [comment]
@roemhildtg 👋 😁

**Comment by green3g** [comment]
Netlify looks super handy. Gonna look into that :)

**Comment by tmcgee** [comment]
Credit goes to @amcgee for that netlify thing.

**Pull request merged**
