### PR TITLE
a little housekeeping

### PR DESCRIPTION
**Pull request by btfou**

### CODE REVIEW

**Comment by btfou** [comment]
wrong merge

**Comment by tmcgee** [comment]
@cmv/core-committers Should we reverse the merge into develop branch that did occur and have an actual PR? There are a few changes here that I think should be reviewed and discussed.

**Comment by btfou** [comment]
@tmcgee I tried to revert develop but my local repo has issues. Can you revert develop? I'll push a branch and PR these changes for review. Thanks.

**Comment by tmcgee** [comment]
@btfou: the commit has been reverted.

**Pull request closed without merging**
