### PR TITLE
Fix layers drawing order and make esri logo hideable

### PR DESCRIPTION
**Pull request by etes**
- Fixed layer drawing order for dynamic map services.
- Added a parameter to set the option for hiding the esri logo. Important if you have your own basemaps.

### CODE REVIEW

**Comment by gisnovice** [comment]
Just wanted to update for CMV 2.0.0 beta.1 to hide esri logo

go to `viewer\js\config\viewer,js`

add `logo: false` in mapOptions:

for example:
` 

        //default mapClick mode, mapClickMode lets widgets know what mode the map is in to avoid multipult map click actions from taking place (ie identify while drawing).
        defaultMapClickMode: 'identify',
        // map options, passed to map constructor. see: https://developers.arcgis.com/javascript/jsapi/map-amd.html#map1
        mapOptions: {
            basemap: 'satellite',
            center: [-117.53, 34.23],
            zoom: 12,
            minZoom: 12,
            sliderStyle: 'small',
            logo: false
        },`

**Comment by cmccullough2** [comment]
How can I change the url in the Esri Logo?  I was able to change the logo in my viewer in the api, but not the url?

**Comment by tmcgee** [comment]
@cmccullough2 I would not recommend changing the logo or the url within the API. It is possible that Esri might disapprove 😨 but perhaps more important is it could be hard to manage going forward as the reference/resource you modify could change in future versions of the API.

I suggest using `logo: false` to hide the Esri logo (accepted and documented approach) then position your own logo+url on the map with basic html/css or a simple widget.

**Comment by cmccullough2** [comment]
@tmcgee Well that is a much better approach. Thanks

**Pull request closed without merging**
