### PR TITLE
Sub layer support

### PR DESCRIPTION
**Pull request by AlexAThomas**
These changes allow the user to have granular control over each subLayer
in a dynamic Map service.  Now, instead of having to just use the name
of the layer in the map, you can override it to whatever you'd like.
you can also redefine the min/max scale of the subLayer.
see the layerInfo properties defined here:
https://developers.arcgis.com/javascript/jsapi/layerinfo-amd.html

In addition to the subLayerInfo support, i've added two other properties
to the layerControlLayerInfos object.
1) subLayerInfos : array of layerInfos that should override the dynamic
map service's default layerInfos
2) excludedLayers : an array of layer ids that should not be exposed in
the map service
3) includeUnspecifiedLayers: boolean --> if true, then all layers in the
dynamic map service will be added, not just the ones listed in
subLayerInfos.  the excludeLayers list will still be honored.

```
layerControlLayerInfos: {
//layerIds: [0, 2, 4, 5, 8, 9, 10, 12, 21]
includeUnspecifiedLayers : true,
excludedLayers : [1,3],
subLayerInfos: [{id:0,name:"Layer
1",defaultVisibility:false} , {id:2,name:"Layer 2"}, {id:4,name:"Layer
3"} ,{id:5,name:"Layer 4"}, {id:8,name:"Layer
5"} ,{id:9},{id:10}, {id:12,name:"Layer 6"},  {id:21,name:"Layer 7"}]
},
```

### CODE REVIEW

**Comment by tmcgee** [comment]
And thanks here too!

**Comment by tmcgee** [comment]
@AlexAThomas Methods specific to the layerControl widget like `_applyLayerControlOptions` and `_mixinLayerInfos` should be in within the widget not in the controller mixin, Can you refactor this PR to reflect that?

**Comment by AlexAThomas** [comment]
@tmcgee Changes made.  The layers are already loaded by the time this widget is starting up, so I added a check for layer-loaded

**Comment by AlexAThomas** [comment]
@tmcgee let me know if you see any other changes I ought to make

**Pull request merged**
