### PR TITLE
Factor Out MapLoader

### PR DESCRIPTION
**Pull request by gobsmack**
Moved loading of map out of Controller and into DefaultMapLoader. Also added error handling on the layers-added event.

### CODE REVIEW

**Comment by btfou** [comment]
@gobsmack The current CMV workflow is to make PRs against the `develop` branch. `master` is the clean latest release. Please resubmit against `develop`. Thanks.

**Comment by gobsmack** [comment]
@btfou Sorry, I'm still getting my GitHub sea legs. I think I did it right this time. Does that mean that when I start working on something else, I should fork the development branch? Because this time I forked "master".

**Comment by btfou** [comment]
@gobsmack No sweat. Just letting you know. Not sure what you're using as a git client. I use source tree. You can make changes in `master` as you did, but to keep your repo clean I suggest creating a new branch from `master` or `develop` (`develop` evolves into the next release).

**Comment by DavidSpriggs** [comment]
@gobsmack Always use the develop branch if you want to submit a PR.

**Pull request closed without merging**
