### PR TITLE
log layer creation errors

### PR DESCRIPTION
**Pull request by green3g**
# Description
Log detailed error message to the console when errors occur creating a layer. These errors are swallowed up due to the way layers are created.

# Checklist

 - [ ] `grunt lint` produces no error messages

### CODE REVIEW

**Comment by green3g** [comment]
ESlint also removed a little bit of code

**Comment by green3g** [comment]
There may be additional logging we could perform along the app loading phase as well. Widget loading perhaps.

**Comment by green3g** [comment]
How did the previous build pass?

**Comment by tmcgee** [comment]
You can't use `console`. Use [`this.handleError(options)`](https://github.com/cmv/cmv-app/blob/develop/viewer/js/viewer/_ControllerBase.js#L90)

**Comment by green3g** [comment]
Ah duh. Those are all "warnings".

**Pull request merged**
