### PR TITLE
Migrate from jshint to eslint

### PR DESCRIPTION
**Pull request by tmcgee**

### CODE REVIEW

**Comment by btfou** [comment]
@tmcgee This has issues and is unmergeable.

**Comment by tmcgee** [comment]
Hmmm.  There were no conflicts when submitted. It most likely the 2 files with proj4 changes that were just merged.  I will review later tonight.

**Comment by btfou** [comment]
Just a heads up :)

**Comment by tmcgee** [comment]
@btfou: good to go now.

**Comment by btfou** [comment]
Good work. Looking forward to pulling this in.

**Pull request merged**
