### PR TITLE
Add nls support in config files, add pt-pt translation

### PR DESCRIPTION
**Pull request by iled**
These commits add a complete Portuguese (pt-pt) translation to CMV, including:

* all core widgets
* viewer main menu
* other config files
* page titles

`viewer.js` and the other config files didn't have support for nls, so it was also added. All input text included in each config file is stored in `nls/main.js`. E.g.,

```javascript
// http://dojotoolkit.org/reference-guide/1.10/dojo/i18n.html
define({
    root: {
        basemaps: {
            ...
        },
        bookmarks: {
            ...
        },
        otherWidget: {
            ...
        },
        viewer: {
            operationalLayers: {
                damageAssessment: 'Damage Assessment',
            },
            titles: {
                header: 'Configurable Map Viewer',
                pageTitle: 'Configurable Map Viewer',
                subHeader: 'make it your own'
            },
            widgets: {
                bookmarks: 'Bookmarks',
                directions: 'Directions',
                draw: 'Draw',
                ...
            }
        }
    },
    'pt-pt': true
});
```

Other changes included:

* dropped a deprecated layer reference in `config/identify.js`
* normalized keys to camelCase format, in cases where they were PascalCase or kebab-case
* add Null Island bookmark, as suggested by @tmcgee 

I started this translation by [forking](https://github.com/iled/cmv-app-i18n) a [repo](https://github.com/carrbrpoa/cmv-app-i18n) by @carrbrpoa.

### CODE REVIEW

**Comment by tmcgee** [comment]
@iled travis found some eslint errors. indentation in some of pt-pt resource files and a 3 missing semicolons :wink: in config files. the errors are spelled out in the log [here](https://travis-ci.org/cmv/cmv-app/builds/144874753). If you run the `grunt lint` command on your local copy, you can see the errors there too.

@DavidSpriggs thoughts?

**Comment by iled** [comment]
Fixed eslint erros.

Reverted renaming Esri basemaps.

**Comment by tmcgee** [comment]
@iled all looks good to me.

Let's see if @DavidSpriggs has any comments about the approach I recommended for i18n in the config files.

**Comment by DavidSpriggs** [comment]
Looks good. Pulling in the i18n works for now. If we ever want pure Jason config files we will have to rethink this approach. This occurs in other places too.

**Comment by DavidSpriggs** [comment]
Thanks @iled !

**Pull request merged**
