### PR TITLE
Switch Street View widget to use Font Awesome Text Symbol.

### PR DESCRIPTION
**Pull request by tmcgee**

### CODE REVIEW

**Review by amcgee — APPROVED** [review]
👍 

Street View probably doesn't work now with the new Google Maps terms?

**Comment by tmcgee** [comment]
It works when a maps API key is provided. None is included with cmv or our demo.

**Comment by amcgee** [comment]
Got it.  Might want to remove it from the demo.

**Comment by tmcgee** [comment]
I've consider that. Or remove the bogus key so the preview works but with the wonderful new warning Google added of `For Development Purposes only` or similar. I hear that is the latest trend on the web. Seems quite popular... :wink:

**Pull request merged**
