### PR TITLE
Add new `_createMap` method to allow custom mixins to override

### PR DESCRIPTION
**Pull request by tmcgee**
the method.

This is useful when using CMV with BootstrapMap (https://github.com/Esri/bootstrap-map-js).

### CODE REVIEW

**Comment by DavidSpriggs** [comment]
@tmcgee Looks like a merge is needed. Let me know when you have it ready and I will merge.

**Comment by tmcgee** [comment]
@DavidSpriggs what happened? It passed previously: https://travis-ci.org/cmv/cmv-app/builds/97317217

Was there a reason you merged the develop branch back into this branch?

**Comment by DavidSpriggs** [comment]
@tmcgee I merged the prior PR and then this one was out of date. I hit the now greyed out 'update branch' button (as this was recomended by github). Looks like the update branch failed due to this error in the build:
1059: Warning: Cannot read config file: /home/travis/build/cmv/cmv-app/.eslintrc

Did something happen to the .eslintrc file?

**Comment by DavidSpriggs** [comment]
See https://travis-ci.org/cmv/cmv-app/builds/102021972#L1060

**Comment by tmcgee** [comment]
I saw the travis errors which occurred after the merge from develop. The error makes no sense as .eslintrc is in both branches and untouched.

I do not know why the "Update branch" would have been required. Not going to figure out why. I've compared my local branch to the current develop branch and there are no issues. I will kill this PR, delete the branch on GitHub and start over...

**Pull request closed without merging**
