### PR TITLE
Added support to add & remove layer(s) from the Layer Control

### PR DESCRIPTION
**Pull request by AlexThomasEOG**
//add new layer
function _setupSampleLayer(args) {
var layer = args.layer;
var target = args.target;
layer.setVisibility(true);
layer.opacity = 1;
for (var i = 0; i < 8; i++) {
var eLayerInfo = layer.layerInfos[i];
eLayerInfo.defaultVisibility = true
}
};
function _loadSampleLayer() {
var imageParameters = new esri.layers.ImageParameters();
imageParameters.layerIds = [0,1,2,3,4,5,6,7];
imageParameters.layerOption =
esri.layers.ImageParameters.LAYER_OPTION_SHOW;
var layer = new
esri.layers.ArcGISDynamicMapServiceLayer("http://<server>/arcgis/rest/services/<service>/MapServer",
{id: "MyMapService",
visible : true,
imageParameters : imageParameters
}
);
layer.on("load", function(args) {
_setupSampleLayer(args);
});
layer.on("error", function(args) {
debugger;
});
this.app.map.addLayer(layer);
this.app.map.on("layer-add-result", function(args) {
var layer = args.layer;
var error = args.error;
var layerInfo = {
title : "My Sample Title",
type : "dynamic",
layer : layer
}
dojo.publish('layerControl/addLayerControls', [[layerInfo]]);
});
}

//remove layer
dojo.publish("layerControl/removeLayerControls", [["My Sample Title"]])

### CODE REVIEW

**Comment by tmcgee** [comment]
Travis check should pass once PR #499 is merged into the develop branch and then this branch is updated from develop branch.

**Comment by DavidSpriggs** [comment]
#499 merged. Please fix so we can review.

**Comment by tmcgee** [comment]
@AlexThomasEOG If you merge the current develop branch from cmv-app into the branch in your repo, then once this PR is reviewed we can commit/merge the changes back into cmv-app repo. Thanks!

**Comment by tmcgee** [comment]
@AlexThomasEOG I see you've adapted the new code to match our code style rules per the travis build process. Much thanks for that extra effort. Looks like the PR is ready to merge.

@btfou: What do you think of these enhancements to LayerControl widget?

**Comment by tmcgee** [comment]
@AlexThomasEOG On Friday I posted a suggested code addition in the gitter chat in case you missed it.

**Comment by AlexThomasEOG** [comment]
Got it, let me take a look and add it in tonight.

I have some other changes that will be helpful with dynamic map services that use custom renderers in the dynamicLayers parameter for ExportMap

**Comment by tmcgee** [comment]
Sounds like the second part is a separate PR.

**Comment by AlexThomasEOG** [comment]
Ah right.  In that case let me keep the changes just limited to layerControl api

**Comment by AlexThomasEOG** [comment]
@tmcgee @btfou Should be good now for a review

**Comment by AlexThomasEOG** [comment]
```javascript
var myLayer;
function _setupSampleLayer(args) {
var layer = args.layer;
var target = args.target;
layer.setVisibility(true);
layer.opacity = 1;
for (var i = 0; i < 8; i++) {
var eLayerInfo = layer.layerInfos[i];
eLayerInfo.defaultVisibility = true
}
};
function _loadSampleLayer(requestedPosition) {
var imageParameters = new esri.layers.ImageParameters();
imageParameters.layerIds = [0,1,2,3,4,5,6,7];
imageParameters.layerOption =
esri.layers.ImageParameters.LAYER_OPTION_SHOW;
myLayer = new
esri.layers.ArcGISDynamicMapServiceLayer("http:///arcgis/rest/services//MapServer",
{id: "MyMapService",
visible : true,
imageParameters : imageParameters
}
);
myLayer.on("load", function(args) {
_setupSampleLayer(args);
});
myLayer.on("error", function(args) {
debugger;
});
this.app.map.addLayer(myLayer );
var signal = this.app.map.on("layer-add-result", function(args) {
	signal.remove()
	var layer = args.layer;
	var error = args.error;
	var layerInfo = {
		title : "My Sample Title",
		type : "dynamic",
		layer : layer,
		position : requestedPosition
	}
	dojo.publish('layerControl/addLayerControls', [[layerInfo]]);
});
}

//

function _removeSampleLayer() {
dojo.publish("layerControl/removeLayerControls", [[myLayer]]);
this.app.map.removeLayer(myLayer);
}




_loadSampleLayer(0);
_removeSampleLayer();
//pause

_loadSampleLayer(1);
_removeSampleLayer();
//pause

_loadSampleLayer(2);
_removeSampleLayer();
```

**Comment by tmcgee** [comment]
@btfou ping

**Pull request merged**
