### PR TITLE
Development

### PR DESCRIPTION
**Pull request by fileunderjeff**

### CODE REVIEW

**Comment by tmcgee** [comment]
@fileunderjeff I don't think you intended to submit that PR specific to your project directly to the CMV repo.

**Comment by fileunderjeff** [comment]
Yep - sorry about that.

Jeff Reichman
January Advisors <http://www.januaryadvisors.com/>
713.893.7930 . 832.477.7189 (m)
my story <http://linkd.in/QL0GW8> . @fileunderjeff
<http://www.twitter.com/@fileunderjeff> . news and new tunes
<http://januaryadvisors.com/newsletter/>

**Comment by tmcgee** [comment]
not a problem. we all do that kind of thing. I'll close this PR.

As an aside: I see you added an `_IdentifyMixin` to my Attributes Table widget. I didn't examine the specific code but is that possibly something that might be a PR candidate for that widget?

**Comment by fileunderjeff** [comment]
It could be.  Our app is searching across multiple layers of a map
service.  I believe we are using _IdentifyMixin to identify the layer, and
each layer result is a record in the attribute table.  I will have to
double check, but if you think that is useful, it's there for you!

**Pull request closed without merging**
