### PR TITLE
updated basemaps widget combining agol and custom basemaps

### PR DESCRIPTION
**Pull request by tmcgee**

### CODE REVIEW

**Comment by tmcgee** [comment]
As I experiment with this further, it appears that ESRI has limited the `esri/basemaps` to their Tiled Map Service, OpenStreetMap and Vector Tile layers. Others like WebTiled, WMS, Dynamic Map Service and Image Map Service layers are not supported.

I will keep this PR open for any additional discussion and potential revision but it should not be committed as is.

**Comment by tmcgee** [comment]
I have restored the `custom` mode so we have the original functionality PLUS the ability to include custom basemaps of the supported types to `esri/basemaps`.

@DavidSpriggs Ready for review and merge.

**Comment by DavidSpriggs** [comment]
@tmcgee Merge prior into this PR.

**Comment by tmcgee** [comment]
@DavidSpriggs done.

**Pull request merged**
