### PR TITLE
Fix/helpdijit menu icons

### PR DESCRIPTION
**Pull request by ishiland**
# Description
Fix Help dijit menu icons in reference to #888 

# Checklist

 - [ X] `grunt lint` produces no error messages

### CODE REVIEW

**Comment by tmcgee** [comment]
@ishiland Thanks for the contribution! Is this fix applicable to all other TabContainers as well as the Help widget?

**Comment by ishiland** [comment]
Thats a good question, you are probably right. I assume the change would go in viewer/css/cmv.css if that is the case? I'd be glad to submit a new PR after confirming the issue.

**Comment by tmcgee** [comment]
@ishiland After some research, the best place for this is actually in the flat dijit theme. When I converted the flat icons to use Font Awesome, I missed these tab strip icons because they do not appear in the tests used with that theme.

I have added them to the theme and will update the CMV repo. I will close this PR once the update is done. Note to self, the repo containing the modified flat dijit theme is not on GitHub.

I appreciate you finding this omission and providing the CSS classes. 👍

**Comment by ishiland** [comment]
@tmcgee sounds good, glad you got it figured out!

**Pull request closed without merging**
