### PR TITLE
Add icon to menu topic

### PR DESCRIPTION
**Pull request by roemhildtg**
This allows for developers to modify a domNode next to the layer name when a menu click happens, for example set a font-awesome class or modify the inner html. One potential issue is the iconNode won't work with multiple icons, only one is shown at a time even if multiple font-awesome classes are set on it. 

Something like this is a possibility:
capture

```JavaScript
             if (r.iconNode) {
                if (domClass.contains(r.iconNode, 'fa-fire')) {
                    domClass.remove(r.iconNode, this.cssClasses);
                } else {
                    domClass.add(r.iconNode, this.cssClasses);
                }
            }
```

Open to suggestions and discussion!

### CODE REVIEW

**Comment by DavidSpriggs** [comment]
@roemhildtg Neat idea. Can use explain a use case for this?

**Comment by roemhildtg** [comment]
Hi @DavidSpriggs, one use case could be if a widget temporarily affects that sublayer like setting a definition query or temporarily adding a heatmap an icon could toggle to notify the user of the action on that layer

**Comment by tmcgee** [comment]
Another use case would be to open a tab in the attribute table widget with query results displayed from that sub layer. That would be pretty trivial to configure. You could toggle the icon to a "busy" indicator while the query is running.

**Comment by tmcgee** [comment]
@DavidSpriggs: I am in favor of merging this PR as part of 1.3.4.

**Comment by btfou** [comment]
Merged https://github.com/cmv/cmv-app/commit/86cd2fc77124bace286b21ea8bb33dc5cb615b75

**Comment by btfou** [comment]
@roemhildtg Could you please add docs for this in https://github.com/cmv/cmv-docs/blob/master/widgets/LayerControl.md. Thanks.

**Comment by tmcgee** [comment]
That request for updated documentation would also apply to the shiny new enhancements added in #401

**Comment by roemhildtg** [comment]
Will do. I have a metadata widget that I could include as a basic sample, what do you guys think would be the best way to include it @btfou @tmcgee? 

The widget works with these enhancements and waits for its menu item topic to be published, then it queries the rest server of the layer and opens a dialog with the metadata content.

**Comment by tmcgee** [comment]
@roemhildtg thanks. Do you have the metadata widget accessible in a repo?

**Comment by roemhildtg** [comment]
Not currently, but I can upload it to my repo.

**Comment by tmcgee** [comment]
Thanks. That would help the current discussion AND the CMV community. :smile:

**Comment by roemhildtg** [comment]
No problem, [I added two examples, the heatmap and the metadata dialog](https://github.com/roemhildtg/CMV_Widgets/tree/master/widgets)

**Pull request merged**
