### PR TITLE
Introduce Bower

### PR DESCRIPTION
**Pull request by btfou**
Basic usage for now. Pulling in helpful packages like proj4.

Also added grunt tasks to copy them.

It's all optional and doesn't not affect CMV as it is now setup or operates.

### CODE REVIEW

**Comment by tmcgee** [comment]
I am not the best to comment on this addition since I do not use bower or grunt tasks with cmv. That is because for implementations done in conjunction with my clients, grunt/bower adds an extra layer of complexity that my clients do not necessarily want or need. I realize that I can just ignore this potential addition as it is currently proposed and things will work as is. My only concern would be that grunt/bower not become a cmv requirement down the road. 

Perhaps others that use grunt/bower can provide additional feedback.

Additional thought: since none of the projects given as examples are used by the core cmv app, this might be better provided as a separate example of using bower as opposed to added to core. thoughts?

**Comment by tmcgee** [comment]
@btfou: I said before that I'm probably not the best to comment on the grunt/bower benefits in this PR. That doesn't mean it is a bad idea! :) If you get no additional feedback from the other @cmv/core-committers, why don't you resolve the minor conflicts and we get this PR committed. thoughts?

**Comment by btfou** [comment]
It's one step closer to builds, great for pulling in libs, and with the API coming to bower anytime, it's needed. I'm also finding it very useful in a restricted environment where all resources must be internal.

I think what might be more useful is to close this now. Then reintroduce with grunt-dojo as an option to build (by default continuing to use cdn). The performance gains wrapping up widgets, layers, and templates into a build layer are impressive. Especially with IE.

**Comment by DavidSpriggs** [comment]
I think we should do it for the reasons Ben points out. Looks like we have a conflicts in the PR now. Ben, can you fix it and then we will merge it.

**Comment by btfou** [comment]
@DavidSpriggs I'm going to close this. @tmcgee has a revamped Controller coming. I assumed there'd be another version bump following soon after. I want to scrape together my bits and pieces and PR against that version with a well thought out PR. Including stylus and a few other grunt goodies.

**Pull request closed without merging**
